// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoaxbyzisvndqouynmcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvYXhieXppc3ZuZHFvdXlubWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MDc0MjUsImV4cCI6MjA2NjQ4MzQyNX0.cNQbLSsIhrg9Hev8bEG_yvqHT5hGXqzFILh_sIK6UVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);